### ISSUE TITLE
May I ask if it is still usable now?

### ISSUE THREAD

**Issue by IGNiT3-R** [JackCui001/TeamSpeakUnlocker#1]
how can I use it?

**Comment by JackCui001** [comment]
Only work on 3.4.3 version of Android TeamSpeak. Use Xposed-like framework to inject.
Please notice that this is a demo project. It is highly possible it can't work well now.

**Comment by IGNiT3-R** [comment]
> Only work on 3.4.3 version of Android TeamSpeak. Use Xposed-like framework to inject.  Please notice that this is a demo project. It is highly possible it can't work well now.

大佬，这个lsp框架可以用吗？我应该先把他变成apk然后安装吗？抱歉，不太懂这个

**Comment by JackCui001** [comment]
> > Only work on 3.4.3 version of Android TeamSpeak. Use Xposed-like framework to inject.  Please notice that this is a demo project. It is highly possible it can't work well now.
> 
> 大佬，这个lsp框架可以用吗？我应该先把他变成apk然后安装吗？抱歉，不太懂这个

可用，需要自己打包编译成apk、签名然后安装。

**Comment by IGNiT3-R** [comment]
> > > Only work on 3.4.3 version of Android TeamSpeak. Use Xposed-like framework to inject.  Please notice that this is a demo project. It is highly possible it can't work well now.
> > 
> > 
> > 大佬，这个lsp框架可以用吗？我应该先把他变成apk然后安装吗？抱歉，不太懂这个
> 
> 可用，需要自己打包编译成apk、签名然后安装。

感谢 我去试试
