### ISSUE TITLE
貌似无法连接

### ISSUE THREAD

**Issue by 577fkj** [JackCui001/TeamSpeakUnlocker#2]
![image](https://github.com/JackCui001/TeamSpeakUnlocker/assets/86393520/090860e3-149e-4d44-a4bd-d5dd07287a88)

从外网上下载到的3.4.3的apk安装后无法连接到服务器
不知道是不是客户端哪里有问题
服务器是没问题的
能否提供下3.4.3的apk😔

**Comment by JackCui001** [comment]
已知问题，无法确定是TS验证机制导致的还是软件自身问题，暂时无法解决。

**Comment by 577fkj** [comment]
> 已知问题，无法确定是TS验证机制导致的还是软件自身问题，暂时无法解决。

已解决 native 中也有验证
低调使用 请勿传播 https://pan.fkj233.cn/Alipan/Teamspeak/Teamspeak_3.4.5-336-lspatched.apk

**Comment by JackCui001** [comment]
> > 已知问题，无法确定是TS验证机制导致的还是软件自身问题，暂时无法解决。
> 
> 已解决 native 中也有验证 低调使用 请勿传播 https://pan.fkj233.cn/Alipan/Teamspeak/Teamspeak_3.4.5-336-lspatched.apk

感谢，没考虑过native层，有时间的话我可能会去完善一下。

**Comment by 577fkj** [comment]
> > > 已知问题，无法确定是TS验证机制导致的还是软件自身问题，暂时无法解决。
> > 
> > 
> > 已解决 native 中也有验证 低调使用 请勿传播 https://pan.fkj233.cn/Alipan/Teamspeak/Teamspeak_3.4.5-336-lspatched.apk
> 
> 感谢，没考虑过native层，有时间的话我可能会去完善一下。

可以参考下我的这个
[577fkj/TSThreeUnlock](https://github.com/577fkj/TSThreeUnlock)
