### ISSUE TITLE
试了下不太起作用

### ISSUE THREAD

**Issue by thunder-sword** [JackCui001/TeamSpeakUnlocker#3]
虽然进去界面了，但是不管连接什么服务器都是显示：server connection could not be initialized。有办法解决吗？

![e7c6052da6b3af13be04b24140753247](https://github.com/user-attachments/assets/a60c457d-3431-4e36-af5d-14ca48254897)

**Comment by JackCui001** [comment]
服务器鉴权过程中部分逻辑可能在so动态链接库中实现，本人暂时没有能力分析与hook此部分代码，抱歉。
